chore: improve CSpell failure reporting and handling

diff --git a/.github/workflows/spellcheck.yaml b/.github/workflows/spellcheck.yaml
--- a/.github/workflows/spellcheck.yaml
+++ b/.github/workflows/spellcheck.yaml
@@ -13,13 +13,15 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Run CSpell
+        id: cspell
         uses: streetsidesoftware/cspell-action@v6
         with:
           config: "./cspell.json"
           incremental_files_only: false
+        continue-on-error: true
 
-      - name: Show message on CSpell failure
-        if: failure() # This conditional makes the step run only on failure
+      - name: Report CSpell Failure
+        if: steps.cspell.outcome == 'failure'
         run: |
-          echo "❌ Spell check failed."
-          echo "Is it a false error? Custom words can be added to ./.cspell/maintainer-words.txt"
+          echo "::error::🛑 Spell check failed. Please fix the spelling issues listed above."
+          exit 1
